[scan]
  input_directory = "data/input"
  output_directory = "data/output"

[ui]
  columns_per_row = 2
  rows_per_page = 27

[format]
  target_format_file = "configs/target_format.xlsx"
  target_sheet = "Sheet1"
  formula_row = 50
  table_end_tolerance = 2